### ISSUE TITLE
only check in date picker

### ISSUE THREAD

**Issue by umerawan86** [crazychicken/t-datepicker#1]
This date picker is just awesome, can you please tell me is there any way to work with only one date picker, I mean there is no date range, only one date picker and after selecting date, picker will close.

**Comment by crazychicken** [comment]
thank you for using t-datepicker, Currently, i focus on develop date range function, issue about function only one date picker i will try develop next version.

**Comment by tutnm** [comment]
@umerawan86 you can view demo https://t-datepicker.getqwerty.com/demo-only-calendar.html

**Comment by umerawan86** [comment]
Thanks a lot for the quick reply and assistance.

**Comment by tutnm** [comment]
One star. If you like it. LOL =))
