### ISSUE TITLE
Highlighted switches not working

### ISSUE THREAD

**Issue by arwystli** [crazychicken/t-datepicker#11]
I was having trouble getting highlighting to switch off, look into the code and found a solution to get settings.toDayHighlighted and settings.nextDayHighlighted to work, here is a diff:
--- t-datepicker_1.js   2018-12-12 11:32:31.000000000 +0000
+++ t-datepicker_2.js   2018-12-13 17:03:15.545034596 +0000
@@ -827,7 +827,7 @@
         if ( Number(dayselect) === dataUTC[0] ) {
           var this_picker = $(toDayElement[i]).parents('.t-datepicker')
           if ( this_picker.find('.t-input-check-in').val() !== 'null'
-          || settings.toDayHighlighted !== false ) {
+          && settings.toDayHighlighted !== false ) {
             toDayElement[i].className = 't-start';
           }
         }
@@ -835,7 +835,7 @@
         if ( Number(dayselect) === dataUTC[1] ) {
           var this_picker = $(toDayElement[i]).parents('.t-datepicker')
           if ( this_picker.find('.t-input-check-out').val() !== 'null'
-          || settings.nextDayHighlighted !== false ) {
+          && settings.nextDayHighlighted !== false ) {
             toDayElement[i].className = 't-end';
           }
         }

**Comment by crazychicken** [comment]
Hi @arwystli ,

I have not yet clearly understood your mean.
But i have many suggestion for you:
Options:
- toDayShowTitle
- dateRangesShowTitle
First view:
- toDayHighlighted
- nextDayHighlighted

Clear all title, you can use:
```
$('.t-datepicker').tDatePicker({
  toDayShowTitle:false,
  dateRangesShowTitle:false,
  toDayHighlighted:false,
  nextDayHighlighted:false
})
```

I hope this explains the situation for you.

**Comment by arwystli** [comment]
Thank you for the prompt reply!
I have already set those settings to false but the highlighting did not stop. I am only using one calendar so no 'check out' date, just a number of days input from which I can figure it out.

Using '&&' instead of '||' solves the problem. In my experience this happens when the two items being 'OR'ed are both 'NOT', in that case AND or '&&' is needed.

Changing the line (829)
if ( this_picker.find('.t-input-check-in').val() !== 'null'
to
if ( this_picker.find('.t-input-check-in').val() !== ''

switched off the toDayHighlighted but doing the same for t-input-check-out did not work, possibly because I am not using your check-out feature eg a second calendar.

Apart from this very minor niggle the calendar works well, lightweight and easy to style. Thanks.

**Comment by crazychicken** [comment]
Hi @arwystli,

If you want to use one calendar and you want to stop highlighting.
You can view [demos](https://t-datepicker.getqwerty.com/demo-only-calendar.html), [callOnlyPicker](https://t-datepicker.getqwerty.com/installation.html#callOnlyPicker)

Option [dateRangesHover](https://t-datepicker.getqwerty.com/options.html#dateRangesHover)
```
$('.t-datepicker').tDatePicker({
  autoClose: true,
  numCalendar : 1,
  dateRangesHover: false
});
```

Or you can change style css with 
```
.t-range {
  background : 'color_theme';
  color      : 'color_theme';
}
```
I hope this the answer may help you.

**Comment by arwystli** [comment]
tweaking the css is the best method as it does future-proof the js.

.t-check-in .t-end,
.t-check-out .t-start,
.t-check-out tr ~ .t-end {
  background: #fff;
  color: #495057;
}

Thanks for your help.
