### ISSUE TITLE
How to customize date format style?

### ISSUE THREAD

**Issue by keem1201** [crazychicken/t-datepicker#3]
First of all, I would like to thank you very much for this awesome datepicker plugin.

Ok...

It is possible to customize the date format style on input form as something like this:

[http://themebubble.com/demo/hotelluxe/video/](http://themebubble.com/demo/hotelluxe/video/)

Thanks

**Comment by crazychicken** [comment]
Hi @keem1201,
About  the date format style on input.
You can check options pages t-datepicker:
https://t-datepicker.getqwerty.com/options.html#showDateTheme

```
$('.t-datepicker').tDatepicker({
  // Default data date, if you want you can change it.
  titleMonths:['January','February','March','April','May','June','July','August','Septemper','October','November','December'],
  titleMonthsLimitShow:'3',  // Max length of item your data months 
  showDateTheme:'dd-mm' // Custom show date
})
```
About the style, you have to custom your css.

Please, tell me if there is anything i could help with this problem!
