### ISSUE TITLE
't-special-day' doesnt show for none defualt months

### ISSUE THREAD

**Issue by vajiraHOA** [crazychicken/t-datepicker#5]
Hi There,

Great Tool!

A question/issue:  The special days will only display on load for the first two months (in show mode) in focus. The special days do not show up default for other months when you are scrolling through the calendar. 

They will show up once you select a date on any of the months in focus.

See screenshots attached.

Any chance this can get fixed?

![1](https://user-images.githubusercontent.com/27320758/46664281-15a8f880-cc08-11e8-9665-7c64748364d2.png)

![2](https://user-images.githubusercontent.com/27320758/46664261-088c0980-cc08-11e8-84fc-7ea3683a107f.png)

**Comment by vajiraHOA** [comment]
I figured out that this was happening across two different years. This is because of the following line:

Line: 786
`if (settings.fnDataEvent[key] != undefined && getMonths === m) {`

I have updated the function as below to achieve what I require

```
var getDays = Number(toDayElement[i].getAttribute('data-t-date'));
var getMonths = new Date(getDays).getMonth() + 1;
var key = gYear + '-' + check_num_10(gMonth) + '-' + check_num_10(getNum);
var nextyearkey = gYear+1 + '-' + check_num_10(gMonth) + '-' + check_num_10(getNum);

if (settings.fnDataEvent[key] != undefined && getMonths === m) {
	var cln = toDayElement[i].className;
	toDayElement[i].className = toDayElement[i].className.replace(' t-special-day t-disabled', '') + ' t-special-day t-disabled';
	toDayElement[i].setAttribute('t-date-title', check_num_10(getNum) + ' ' + settings.titleMonths[new Date(getDays).getMonth()] + ' - ' + settings.fnDataEvent[key])
}else if(settings.fnDataEvent[nextyearkey] != undefined && getMonths === 1){
	var cln = toDayElement[i];
	toDayElement[i].className = toDayElement[i].className.replace(' t-special-day t-disabled', '') + ' t-special-day t-disabled';
	toDayElement[i].setAttribute('t-date-title', check_num_10(getNum) + ' ' + settings.titleMonths[new Date(getDays).getMonth()] + ' - ' + settings.fnDataEvent[key])
}
```

**Comment by crazychicken** [comment]
Hi @vajiraHOA,
I'm sorry for late replying.
I have just updated version 1.0.3 with **fnDataEvent** and option **mergeDataEvent**.

You can try again now or view document here [t-datepicker.getqwerty.com](https://t-datepicker.getqwerty.com/options.html#mergeDataEvent)

This is the [demo](https://codepen.io/tuds/pen/YJvGyO)

Thank you so much.
